name: "fuzzywuzzy"
version: "0.1.5"
homepage: "https://github.com/sphericalkat/dart-fuzzywuzzy"
description: An implementation of the popular fuzzywuzzy package in Dart, to suit all your fuzzy string matching/searching needs!
repository: "https://github.com/sphericalkat/dart-fuzzywuzzy"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0

dev_dependencies:
  test:
  test_coverage: ^0.4.2
  pedantic: ^1.11.0