name: Release to GitHub releases

on:
  push:
    branches:
      - main

jobs:
  release_to_ghr:
    name: Release to GitHub releases
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release to github releases
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-file: CHANGELOG.md